### PR TITLE
Linux fix handler

### PR DESCRIPTION
**Pull request by JonasSchiott**
Fixed linux command and event handler

### CODE REVIEW

**Comment by anishshobithps** [comment]
The command handler, was started from the episode 2 , is it only changed in Episode 7 code? Or is it the same in other episode codes too?, don't you think that people can make a clone from any branch?

**Comment by JonasSchiott** [comment]
> The command handler, was started from the episode 2 , is it only changed in Episode 7 code? Or is it the same in other episode codes too?, don't you think that people can make a clone from any branch?

Indeed, we need to fix all of them

**Comment by MelodicAlbuild** [comment]
You could just branch copy all of them, but I would recommend going and testing each one to make sure no other code breaks

**Comment by JonasSchiott** [comment]
> You could just branch copy all of them, but I would recommend going and testing each one to make sure no other code breaks

I've helped various people changing this! We should continue the conversation in the private server for ease and further testing!

**Comment by Strandxo** [comment]
PR once this further testing has been completed, thanks.

**Pull request closed without merging**
